//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
// Generated on: 2018.03.13 at 02:19:09 PM CET 
=======
// Generated on: 2018.03.13 at 01:29:59 PM CET 
>>>>>>> d6f44158f7c6df7925e754fa2e082bc12faa298b
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._8080.soap;
