//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.14 at 02:40:08 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._8080.soap;
